package constants

const (
	PORT = "PORT"
	// const localize
	FAILED_OPEN_FILE = "FAILED_OPEN_FILE"
	EMAIL_TAKEN      = "EMAIL_TAKEN"
	USER_NOT_FOUND   = "USER_NOT_FOUND"

	MONGO_HOST          = "MONGO_HOST"
	MONGO_PORT          = "MONGO_PORT"
	MONGO_TYPE          = "MONGO_TYPE"
	MONGO_OPTION        = "MONGO_OPTION"
	MONGO_USERNAME      = "MONGO_USERNAME"
	MONGO_PASSWORD      = "MONGO_PASSWORD"
	MONGO_DATABASE_NAME = "MONGO_DATABASE_NAME"

	CLOUD_NAME       = "CLOUD_NAME"
	CLOUD_API_KEY    = "CLOUD_API_KEY"
	CLOUD_API_SECRET = "CLOUD_API_SECRET"

	REDIS_URL      = "REDIS_URL"
	REDIS_USERNAME = "REDIS_USERNAME"
	REDIS_PASSWORD = "REDIS_PASSWORD"
	REDIS_HOST     = "REDIS_HOST"
	REDIS_PORT     = "REDIS_PORT"
	REDIS_DB       = "REDIS_DB"

	MESSAGE_ERROR_FILE_PARAMS_REQUIRED = "File params required"
	SECRET                             = "SECRET"

	STATUS = "status"
	DATA   = "data"
	ERROR  = "error"

	SUCCESS = "Success"
	FAILED  = "Failed"

	FOLDER = "folder"

	ERROR_MESSAGE = "error_message"

	MESSAGE_SUCCESS_UPDATE_USER         = "Success Update User"
	MESSAGE_SUCCESS_UPDATE_WEDDING_DATA = "Success Update Wedding Data"

	MESSAGE_ERROR_FAILED_CREATE_USER         = "Failed to create User"
	MESSAGE_ERROR_FAILED_UPDATE_DATA         = "No Data Updated"
	MESSAGE_ERROR_FAILED_EXTRACT_INSERTED_ID = "Failed to extract inserted ID"
)
