package constants

const (
	PORT = "PORT"

	MONGO_HOST          = "MONGO_HOST"
	MONGO_PORT          = "MONGO_PORT"
	MONGO_TYPE          = "MONGO_TYPE"
	MONGO_OPTION        = "MONGO_OPTION"
	MONGO_USERNAME      = "MONGO_USERNAME"
	MONGO_PASSWORD      = "MONGO_PASSWORD"
	MONGO_DATABASE_NAME = "MONGO_DATABASE_NAME"

	CLOUD_NAME       = "CLOUD_NAME"
	CLOUD_API_KEY    = "CLOUD_API_KEY"
	CLOUD_API_SECRET = "CLOUD_API_SECRET"

	REDIS_URL      = "REDIS_URL"
	REDIS_USERNAME = "REDIS_USERNAME"
	REDIS_PASSWORD = "REDIS_PASSWORD"
	REDIS_HOST     = "REDIS_HOST"
	REDIS_PORT     = "REDIS_PORT"
	REDIS_DB       = "REDIS_DB"

	SECRET = "SECRET"

	STATUS = "status"
	DATA   = "data"
	ERROR  = "error"

	SUCCESS = "Success"
	FAILED  = "Failed"

	FOLDER = "folder"

	ERROR_MESSAGE = "error_message"

	LOCALE_ENGLISH   = "en"
	LOCALE_INDONESIA = "id"
)
